version: '3.1'

services:
    mongo-container:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=test
            - MONGO_INITDB_ROOT_PASSWORD=Passw0rd
        ports:
            - 27017:27017
        volumes:
            - mongo-data:/data/db
            - mongo-config:/data/configdb

    # elastic-container:
    #     build: ./es
    #     # ulimits:
    #     #     memlock:
    #     #         soft: -1
    #     #         hard: -1
    #     volumes:
    #         - es-data:/usr/share/elasticsearch/data

volumes:
    mongo-data:
    mongo-config:
    es-data:
